Repository cetmix/cetmix-tower, pull requests merged in 2024-12, with the labels that each got.

#152 [14.0][FIX] cetmix_tower_server: Key creation
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/tests/test_key.py
Labels: needs review, bot is merging ⏳, approved

#149 [14.0] [IMP] cetmix_tower_server: UI improvements
  cetmix_tower_server/data/ir_actions_server.xml
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_plan.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_variable_mixin.py
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_plan_execute_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#155 [IMP] cetmix_tower_server: Enhance UI/UX and add functionalities
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/views/cx_tower_plan_line_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_plan_execute_wizard_view.xml
Labels: needs review, approved

#151 [14.0][IMP] cetmix_tower_server: Update record deletion flow
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/models/cx_tower_file.py
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/models/cx_tower_plan_line_action.py
  cetmix_tower_server/models/cx_tower_plan_log.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/tests/test_plan.py
  cetmix_tower_server/tests/test_server.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#147 [14.0][FIX] cetmix_tower_server: Link secrets to records
  cetmix_tower_server/models/__init__.py
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_file.py
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_key_mixin.py
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/tests/test_file.py
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_file_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#157 [i18n] update italian
  cetmix_tower_server/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: bot is merging ⏳

#153 [14.0][IMP] cetmix_tower_yaml: Secret value check
  .gitignore
  Dockerfile
  cetmix_tower_yaml/models/cx_tower_key.py
  cetmix_tower_yaml/models/cx_tower_server_template.py
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/tests/__init__.py
  cetmix_tower_yaml/tests/test_key.py
  cetmix_tower_yaml/tests/test_server_key.py
  cetmix_tower_yaml/tests/test_server_template.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#154 [IMP] cetmix_tower_server: "Required" flag for configuration variables in Server Template
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/tests/test_server_template.py
  cetmix_tower_server/views/cx_tower_server_template_view.xml
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard.py
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#164 [14.0] cetmix_tower_server Fix translation related issues
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard.py
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/readme/CONTEXT.md
  cetmix_tower_yaml/readme/DESCRIPTION.md
  cetmix_tower_yaml/static/description/index.html
Labels: needs review, bot is merging ⏳

#168 [FIX] cetmix_tower_server: Remove demo data usage in tests
  cetmix_tower_server/tests/common.py
  cetmix_tower_server/tests/test_plan.py
  cetmix_tower_server/tests/test_server.py
Labels: needs review, bot is merging ⏳, approved

#158 [14.0][IMP] cetmix_tower_server: Improve secrets/keys handling
  cetmix_tower_server/README.rst
  cetmix_tower_server/__init__.py
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_file_template.py
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_key_mixin.py
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/tests/test_key.py
  cetmix_tower_server/views/cx_tower_file_template_view.xml
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
Labels: needs review, bot is merging ⏳, approved, ready to merge
