Repository cetmix/cetmix-tower, pull requests merged in 2024-10, with the labels that each got.

#101 [IMP] cetmix_tower_server: add Licence to repo
  LICENSE
Labels: needs review

#99 [14.0][IMP] cetmix_tower_server Improve helpers
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/models/cx_tower_plan.py
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/models/cx_tower_plan_log.py
  cetmix_tower_server/models/cx_tower_reference_mixin.py
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/readme/USAGE.md
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_cetmix_tower.py
  cetmix_tower_server/tests/test_variable.py
Labels: needs review, bot is merging ⏳, approved

#100 [FIX] cetmix_tower_server:t3960 Fix replacing of variables after create server from template
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/tests/test_server_template.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#104 [14.0 t3956 cetmix tower server appearance fixes
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/models/cx_tower_plan.py
  cetmix_tower_server/models/cx_tower_plan_log.py
  cetmix_tower_server/models/cx_tower_server_log.py
  cetmix_tower_server/models/cx_tower_variable_mixin.py
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_file_view.xml
  cetmix_tower_server/views/cx_tower_plan_line_view.xml
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/views/cx_tower_variable_view.xml
Labels: needs review, bot is merging ⏳

#106 [14.0][IMP] cetmix_tower_server File Template references
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_file_template.py
  cetmix_tower_server/readme/CONFIGURE.md
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/cx_tower_file_template_view.xml
Labels: needs review, bot is merging ⏳, approved

#107 [14.0][FIX] t3954 The value of a variable cannot be assigned to several records same time
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/migrations/14.0.0.3.20/pre-migration.py
  cetmix_tower_server/models/cx_tower_plan_line_action.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_plan.py
  cetmix_tower_server/tests/test_variable.py
  cetmix_tower_server/views/cx_tower_variable_value_view.xml
  cetmix_tower_server/views/cx_tower_variable_view.xml
Labels: bot is merging ⏳, approved

#103 [14.0][ADD] cetmix_tower_server_yaml Yaml support for Cetmix Tower
  Dockerfile
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server_yaml/README.rst
  cetmix_tower_server_yaml/__init__.py
  cetmix_tower_server_yaml/__manifest__.py
  cetmix_tower_server_yaml/demo/command_test_yaml.yaml
  cetmix_tower_server_yaml/models/__init__.py
  cetmix_tower_server_yaml/models/cx_tower_command.py
  cetmix_tower_server_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_server_yaml/readme/CONFIGURE.md
  cetmix_tower_server_yaml/readme/CONTEXT.md
  cetmix_tower_server_yaml/readme/DESCRIPTION.md
  cetmix_tower_server_yaml/readme/USAGE.md
  cetmix_tower_server_yaml/static/description/icon.png
  cetmix_tower_server_yaml/static/description/index.html
  cetmix_tower_server_yaml/tests/__init__.py
  cetmix_tower_server_yaml/tests/test_command.py
  cetmix_tower_server_yaml/tests/test_tower_yaml_mixin.py
  cetmix_tower_server_yaml/views/cx_tower_command_view.xml
  requirements.txt
  setup/cetmix_tower_server_yaml/odoo/addons/cetmix_tower_server_yaml
  setup/cetmix_tower_server_yaml/setup.py
Labels: needs review, bot is merging ⏳, approved

#108 [14.0][FIX] cetmix_tower_server Reference generation
  cetmix_tower_server/models/cx_tower_reference_mixin.py
  cetmix_tower_server/tests/test_reference_mixin.py
Labels: needs review, bot is merging ⏳, approved

#109 [14.0][IMP] t3969 cetmix_tower_server: Duplicate flight plan lines
  cetmix_tower_server/models/cx_tower_plan.py
  cetmix_tower_server/tests/test_plan.py
Labels: bot is merging ⏳, approved

#111 [14.0] cetmix_tower_server: file template YAML export/import
  cetmix_tower_server_yaml/i18n/cetmix_tower_server_yaml.pot
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/__init__.py
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/demo/command_test_yaml.yaml
  cetmix_tower_yaml/models/__init__.py
  cetmix_tower_yaml/models/cx_tower_command.py
  cetmix_tower_yaml/models/cx_tower_file_template.py
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/readme/CONFIGURE.md
  cetmix_tower_yaml/readme/CONTEXT.md
  cetmix_tower_yaml/readme/DESCRIPTION.md
  cetmix_tower_yaml/readme/USAGE.md
  cetmix_tower_yaml/static/description/icon.png
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/__init__.py
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_file_template.py
  cetmix_tower_yaml/tests/test_tower_yaml_mixin.py
  cetmix_tower_yaml/views/cx_tower_command_view.xml
  cetmix_tower_yaml/views/cx_tower_file_template_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/cetmix_tower_server_yaml/odoo/addons/cetmix_tower_server_yaml
  setup/cetmix_tower_yaml/odoo/addons/cetmix_tower_yaml
  setup/cetmix_tower_yaml/setup.py
Labels: needs review, bot is merging ⏳, approved

#105 [14.0][IMP] t3555 cetmix_tower_server: Update related entities when variable name was changed
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_file.py
  cetmix_tower_server/models/cx_tower_file_template.py
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/models/cx_tower_template_mixin.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/tests/__init__.py
  cetmix_tower_server/tests/test_update_related_variable_names.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#88 [14.0][IMP] cetmix_tower_server: Run flight plan from another flight plan
  cetmix_tower_server/README.rst
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_file_template.py
  cetmix_tower_server/models/cx_tower_plan.py
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/models/cx_tower_plan_log.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/CONFIGURE.md
  cetmix_tower_server/readme/DESCRIPTION.md
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_plan.py
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_plan_log_view.xml
Labels: needs review, bot is merging ⏳, approved

#112 [14.0][IMP] cetmix_tower_yaml Many2one fields support
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/models/cx_tower_command.py
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/readme/USAGE.md
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_tower_yaml_mixin.py
  cetmix_tower_yaml/views/cx_tower_command_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#94 [14.0][FIX] cetmix_tower_server: Security restrictions on the command wizard path field
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#119 [14.0][IMP] t3995 cetmix_tower_server: references in tags
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_tag.py
  cetmix_tower_server/readme/CONFIGURE.md
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/cx_tower_tag_view.xml
Labels: needs review, bot is merging ⏳, approved

#90 [14.0][IMP]cetmix_tower_server: Set server status from command
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/CONFIGURE.md
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/views/cx_tower_command_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#120 [14.0][FIX] t4003 cetmix_tower_server: Duplicate server template
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/tests/test_server_template.py
Labels: needs review, bot is merging ⏳, approved

#127 [14.0][FIX] cetmix_tower_server: Duplicate server logs
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/tests/test_server.py
Labels: needs review, bot is merging ⏳, approved

#125 [14.0][IMP]cetmix_tower_yaml: Many2many field support
  cetmix_tower_yaml/models/__init__.py
  cetmix_tower_yaml/models/cx_tower_command.py
  cetmix_tower_yaml/models/cx_tower_file_template.py
  cetmix_tower_yaml/models/cx_tower_tag.py
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_file_template.py
  cetmix_tower_yaml/tests/test_tower_yaml_mixin.py
Labels: needs review, bot is merging ⏳, approved

#123 [FIX] cetmix_tower_server: Fix unsupported ssh key format
  cetmix_tower_server/models/cx_tower_server.py
Labels: needs review, bot is merging ⏳, approved

#122 [IMP] cetmix_tower_server,cetmix_tower_server_notify_backend: Move notification features to new module
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/models/cx_tower_plan_log.py
  cetmix_tower_server/readme/DESCRIPTION.md
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server_notify_backend/README.rst
  cetmix_tower_server_notify_backend/__init__.py
  cetmix_tower_server_notify_backend/__manifest__.py
  cetmix_tower_server_notify_backend/models/__init__.py
  cetmix_tower_server_notify_backend/models/cx_tower_command_log.py
  cetmix_tower_server_notify_backend/models/cx_tower_plan_log.py
  cetmix_tower_server_notify_backend/readme/CONFIGURE.md
  cetmix_tower_server_notify_backend/readme/DESCRIPTION.md
  cetmix_tower_server_notify_backend/readme/USAGE.md
  cetmix_tower_server_notify_backend/static/description/icon.png
  cetmix_tower_server_notify_backend/static/description/index.html
  setup/cetmix_tower_server_notify_backend/odoo/addons/cetmix_tower_server_notify_backend
  setup/cetmix_tower_server_notify_backend/setup.py
Labels: needs review, bot is merging ⏳, approved

#126 [14.0][IMP] t4009 cetmix_tower_server: Visual improvements
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_plan_execute_wizard.py
  cetmix_tower_server/wizards/cx_tower_plan_execute_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#128 [FIX] cetmix_tower: Fix ssh key defenition
  cetmix_tower_server/models/cx_tower_server.py
Labels: needs review, bot is merging ⏳, approved

#121 [FIX] cetmix_tower_server_queue: Fix order of command executions that trigger running other plans
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/tests/test_plan.py
  cetmix_tower_server/views/cx_tower_command_log_view.xml
  cetmix_tower_server_queue/models/cx_tower_server.py
Labels: needs review, bot is merging ⏳

#130 Update repo scripts from template
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: needs review, bot is merging ⏳

#124 [14.0] [IMP] cetmix_tower_server: update command access rules
  cetmix_tower_server/security/cx_tower_command_security.xml
  cetmix_tower_server/tests/test_command.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#118 [14.0][FIX] t3952 cetmix_tower_server: Clean up Python command execution
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/tests/common.py
  cetmix_tower_server/tests/test_command.py
Labels: needs review, bot is merging ⏳, approved, ready to merge
