Repository cetmix/cetmix-tower, pull requests merged in 2024-11, with the labels that each got.

#132 [14.0][IMP] cetmix_tower_server Value field is not required in variable values
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/tests/common.py
  cetmix_tower_server/tests/test_cetmix_tower.py
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/tests/test_plan.py
  cetmix_tower_server/tests/test_server_template.py
  cetmix_tower_server/tests/test_update_related_variable_names.py
  cetmix_tower_server/tests/test_variable.py
Labels: needs review, bot is merging ⏳, approved

#136 [i18n] add italian
  cetmix_tower_server/i18n/it.po
  cetmix_tower_server_notify_backend/i18n/it.po
  cetmix_tower_server_queue/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: bot is merging ⏳

#131 [14.0][IMP] cetmix_tower_server: Update demo data
  cetmix_tower_server/demo/demo_data.xml
Labels: needs review, bot is merging ⏳, approved

#134 [14.0][IMP] cetmix_tower_server: UI/UX imporovents
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/models/cx_tower_plan_log.py
  cetmix_tower_server/views/cx_tower_command_log_view.xml
  cetmix_tower_server/views/cx_tower_plan_log_view.xml
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_plan_execute_wizard.py
  cetmix_tower_server/wizards/cx_tower_plan_execute_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#133 [14.0][IMP] cetmix_tower_server: Server Template mods
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/views/cx_tower_server_template_view.xml
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard.py
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#129 [14.0][IMP] cetmix_tower_server: add reference to models
  cetmix_tower_server/models/cx_tower_plan.py
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/models/cx_tower_plan_line_action.py
  cetmix_tower_server/models/cx_tower_reference_mixin.py
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/tests/test_plan.py
  cetmix_tower_server/tests/test_reference_mixin.py
  cetmix_tower_server/views/cx_tower_plan_line_view.xml
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/views/cx_tower_variable_value_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#135 [14.0][FIX] cetmix_tower_server: Custom code can be executed on a single server at once
  cetmix_tower_server/README.rst
  cetmix_tower_server/readme/USAGE.md
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#140 [FIX] cetmix_tower_server Reference generation
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/models/cx_tower_plan_line_action.py
  cetmix_tower_server/models/cx_tower_reference_mixin.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/tests/test_reference_mixin.py
Labels: needs review, bot is merging ⏳, approved

#141 [14.0][FIX] cetmix_tower_server: Reference generation
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/cx_tower_plan_line.py
  cetmix_tower_server/models/cx_tower_plan_line_action.py
  cetmix_tower_server/models/cx_tower_reference_mixin.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/tests/test_reference_mixin.py
Labels: needs review, bot is merging ⏳, approved

#138 [14.0][FIX] cetmix_tower_server: Fix attributes
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/views/cx_tower_variable_value_view.xml
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#142 [14.0][IMP] cetmix_tower_server: References for OS
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_os.py
  cetmix_tower_server/readme/CONFIGURE.md
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/cx_tower_os_view.xml
Labels: needs review, bot is merging ⏳, approved

#145 [14.0][IMP] cetmix_tower_server: Server Logs refs
  cetmix_tower_server/models/cx_tower_server_log.py
  cetmix_tower_server/views/cx_tower_server_log_view.xml
Labels: needs review, bot is merging ⏳, approved

#146 [14.0][IMP] cetmix_tower_yaml Implement granular access, improve UI and UX
  cetmix_tower_server/README.rst
  cetmix_tower_server/readme/CONFIGURE.md
  cetmix_tower_server/security/cetmix_tower_server_groups.xml
  cetmix_tower_server/static/description/images/user_profile.png
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/menuitems.xml
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/__init__.py
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/demo/command_test_yaml.yaml
  cetmix_tower_yaml/demo/demo_data.xml
  cetmix_tower_yaml/models/cx_tower_server_log.py
  cetmix_tower_yaml/models/cx_tower_server_template.py
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/readme/CONFIGURE.md
  cetmix_tower_yaml/readme/USAGE.md
  cetmix_tower_yaml/security/cetmix_tower_yaml_groups.xml
  cetmix_tower_yaml/security/ir.model.access.csv
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/__init__.py
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_tower_yaml_mixin.py
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/tests/test_yaml_import_wizard.py
  cetmix_tower_yaml/views/cx_tower_command_view.xml
  cetmix_tower_yaml/views/cx_tower_file_template_view.xml
  cetmix_tower_yaml/views/cx_tower_plan_view.xml
  cetmix_tower_yaml/views/cx_tower_server_template_view.xml
  cetmix_tower_yaml/views/menuitems.xml
  cetmix_tower_yaml/wizards/__init__.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz_download.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz_download.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz_upload.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz_upload.xml
Labels: needs review, bot is merging ⏳, approved

#148 [14.0] cetmix_tower_server: add files access rules
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/security/cx_tower_file_security.xml
  cetmix_tower_server/tests/test_file.py
  cetmix_tower_server/views/cx_tower_file_view.xml
Labels: needs review, bot is merging ⏳, approved

#150 [14.0][FIX] cetmix_tower_yaml: fix file name generation
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
Labels: needs review, bot is merging ⏳, approved

#144 [14.0][IMP] cetmix_tower_server: Populate reference field
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/migrations/14.0.0.4.0/post-migration.py
  cetmix_tower_server/static/description/index.html
Labels: needs review, approved, ready to merge
