Repository cetmix/cetmix-tower, pull requests merged in 2025-04, with the labels that each got.

#237 [14.0][IMP] cetmix_tower_server: Shortcuts
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/models/__init__.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/models/cx_tower_shortcut.py
  cetmix_tower_server/security/cx_tower_shortcut_security.xml
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/__init__.py
  cetmix_tower_server/tests/test_shortcut.py
  cetmix_tower_server/views/cx_tower_server_template_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/views/cx_tower_shortcut_view.xml
  cetmix_tower_server/views/menuitems.xml
Labels: needs review, bot is merging ⏳, approved

#238 [14.0][IMP] cetmix_tower_server: Variable validation
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/models/cx_tower_variable.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/tests/test_variable.py
  cetmix_tower_server/views/cx_tower_variable_view.xml
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard.py
Labels: needs review, merged 🎉, approved

#239 [14.0][IMP] cetmix_tower_yaml: New models for export
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/models/__init__.py
  cetmix_tower_yaml/models/cx_tower_server_template.py
  cetmix_tower_yaml/models/cx_tower_shortcut.py
  cetmix_tower_yaml/models/cx_tower_variable.py
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/views/cx_tower_shortcut_view.xml
  cetmix_tower_yaml/views/cx_tower_tag_view.xml
Labels: needs review, bot is merging ⏳, approved

#235 [FIX] cetmix_tower_server: Required host key
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/tests/common.py
  cetmix_tower_server/tests/test_plan.py
  cetmix_tower_server/tests/test_server.py
Labels: needs review, bot is merging ⏳

#243 [14.0][IMP] cetmix_tower_server: code clean up
  cetmix_tower_server/README.rst
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/cx_tower_file.py
  cetmix_tower_server/models/cx_tower_file_template.py
  cetmix_tower_server/models/cx_tower_plan_line_action.py
  cetmix_tower_server/models/cx_tower_plan_log.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_server_log.py
  cetmix_tower_server/readme/HISTORY.md
  cetmix_tower_server/readme/newsfragments/.gitkeep
  cetmix_tower_server/readme/newsfragments/4515.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/tests/test_server.py
  cetmix_tower_server/tests/test_server_template.py
  cetmix_tower_server/tests/test_update_related_variable_names.py
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#245 [16.0][MIG] cetmix_tower_yaml
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/__init__.py
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/demo/demo_data.xml
  cetmix_tower_yaml/i18n/cetmix_tower_yaml.pot
  cetmix_tower_yaml/i18n/hr.po
  cetmix_tower_yaml/i18n/it.po
  cetmix_tower_yaml/models/__init__.py
  cetmix_tower_yaml/models/cx_tower_command.py
  cetmix_tower_yaml/models/cx_tower_file_template.py
  cetmix_tower_yaml/models/cx_tower_key.py
  cetmix_tower_yaml/models/cx_tower_os.py
  cetmix_tower_yaml/models/cx_tower_plan.py
  cetmix_tower_yaml/models/cx_tower_plan_line.py
  cetmix_tower_yaml/models/cx_tower_plan_line_action.py
  cetmix_tower_yaml/models/cx_tower_server_log.py
  cetmix_tower_yaml/models/cx_tower_server_template.py
  cetmix_tower_yaml/models/cx_tower_shortcut.py
  cetmix_tower_yaml/models/cx_tower_tag.py
  cetmix_tower_yaml/models/cx_tower_variable.py
  cetmix_tower_yaml/models/cx_tower_variable_option.py
  cetmix_tower_yaml/models/cx_tower_variable_value.py
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/pyproject.toml
  cetmix_tower_yaml/readme/CONFIGURE.md
  cetmix_tower_yaml/readme/DESCRIPTION.md
  cetmix_tower_yaml/readme/USAGE.md
  cetmix_tower_yaml/security/cetmix_tower_yaml_groups.xml
  cetmix_tower_yaml/security/ir.model.access.csv
  cetmix_tower_yaml/static/description/icon.png
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/__init__.py
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_file_template.py
  cetmix_tower_yaml/tests/test_plan.py
  cetmix_tower_yaml/tests/test_tower_yaml_mixin.py
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/tests/test_yaml_import_wizard.py
  cetmix_tower_yaml/views/cx_tower_command_view.xml
  cetmix_tower_yaml/views/cx_tower_file_template_view.xml
  cetmix_tower_yaml/views/cx_tower_os_view.xml
  cetmix_tower_yaml/views/cx_tower_plan_view.xml
  cetmix_tower_yaml/views/cx_tower_server_template_view.xml
  cetmix_tower_yaml/views/cx_tower_shortcut_view.xml
  cetmix_tower_yaml/views/cx_tower_tag_view.xml
  cetmix_tower_yaml/views/cx_tower_variable_value_view.xml
  cetmix_tower_yaml/views/cx_tower_variable_view.xml
  cetmix_tower_yaml/views/menuitems.xml
  cetmix_tower_yaml/wizards/__init__.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz_download.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz_download.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz_upload.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz_upload.xml
  requirements.txt
Labels: needs review, bot is merging ⏳, approved

#246 [14.0][i18n] updated italian translation
  cetmix_tower_git/i18n/it.po
  cetmix_tower_server/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: bot is merging ⏳

#249 [16.0][MIG] cetmix_tower_git
  cetmix_tower_git/README.rst
  cetmix_tower_git/__init__.py
  cetmix_tower_git/__manifest__.py
  cetmix_tower_git/demo/demo_data.xml
  cetmix_tower_git/i18n/cetmix_tower_git.pot
  cetmix_tower_git/i18n/fi.po
  cetmix_tower_git/i18n/hr.po
  cetmix_tower_git/i18n/it.po
  cetmix_tower_git/models/__init__.py
  cetmix_tower_git/models/cx_tower_file.py
  cetmix_tower_git/models/cx_tower_file_template.py
  cetmix_tower_git/models/cx_tower_git_project.py
  cetmix_tower_git/models/cx_tower_git_project_file_template_rel.py
  cetmix_tower_git/models/cx_tower_git_project_rel.py
  cetmix_tower_git/models/cx_tower_git_remote.py
  cetmix_tower_git/models/cx_tower_git_source.py
  cetmix_tower_git/models/cx_tower_server.py
  cetmix_tower_git/pyproject.toml
  cetmix_tower_git/readme/CONFIGURE.md
  cetmix_tower_git/readme/DESCRIPTION.md
  cetmix_tower_git/readme/USAGE.md
  cetmix_tower_git/security/cx_tower_git_project_file_template_rel_security.xml
  cetmix_tower_git/security/cx_tower_git_project_rel_security.xml
  cetmix_tower_git/security/cx_tower_git_project_security.xml
  cetmix_tower_git/security/cx_tower_git_remote_security.xml
  cetmix_tower_git/security/cx_tower_git_source_security.xml
  cetmix_tower_git/security/ir.model.access.csv
  cetmix_tower_git/static/description/banner.png
  cetmix_tower_git/static/description/icon.png
  cetmix_tower_git/static/description/index.html
  cetmix_tower_git/tests/__init__.py
  cetmix_tower_git/tests/common.py
  cetmix_tower_git/tests/test_file_rel.py
  cetmix_tower_git/tests/test_file_template_rel.py
  cetmix_tower_git/tests/test_project.py
  cetmix_tower_git/tests/test_remote.py
  cetmix_tower_git/tests/test_source.py
  cetmix_tower_git/views/cx_tower_file_template_views.xml
  cetmix_tower_git/views/cx_tower_file_views.xml
  cetmix_tower_git/views/cx_tower_git_project_views.xml
  cetmix_tower_git/views/cx_tower_git_remote_views.xml
  cetmix_tower_git/views/cx_tower_git_source_views.xml
  cetmix_tower_git/views/cx_tower_server_view.xml
Labels: needs review, bot is merging ⏳, approved

#248 [16.0][MIG] cetmix_tower_server_notify_backend
  cetmix_tower_server_notify_backend/README.rst
  cetmix_tower_server_notify_backend/__init__.py
  cetmix_tower_server_notify_backend/__manifest__.py
  cetmix_tower_server_notify_backend/i18n/cetmix_tower_server_notify_backend.pot
  cetmix_tower_server_notify_backend/i18n/it.po
  cetmix_tower_server_notify_backend/models/__init__.py
  cetmix_tower_server_notify_backend/models/cx_tower_command_log.py
  cetmix_tower_server_notify_backend/models/cx_tower_plan_log.py
  cetmix_tower_server_notify_backend/pyproject.toml
  cetmix_tower_server_notify_backend/readme/CONFIGURE.md
  cetmix_tower_server_notify_backend/readme/DESCRIPTION.md
  cetmix_tower_server_notify_backend/readme/USAGE.md
  cetmix_tower_server_notify_backend/static/description/icon.png
  cetmix_tower_server_notify_backend/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#250 [FIX] cetmix_tower_server: Server status widget
  cetmix_tower_server/static/src/components/server_status/server_status_field.esm.js
  cetmix_tower_server/static/src/utils/server_utils.esm.js
Labels: needs review, bot is merging ⏳, approved

#252 Translations update from Hosted Weblate
  cetmix_tower_git/i18n/it.po
  cetmix_tower_server/i18n/it.po
Labels: bot is merging ⏳

#254 [14.0][IMP] cetmix_tower_server: Provide custom variable values directly in command
  cetmix_tower/README.rst
  cetmix_tower/readme/HISTORY.md
  cetmix_tower/readme/newsfragments/.gitkeep
  cetmix_tower/readme/newsfragments/4524.feature
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/newsfragments/4524.feature
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#251 [14.0][IMP] cetmix_tower_server_queue: Cancel stuck jobs
  cetmix_tower/readme/newsfragments/4550.feature
  cetmix_tower_server_queue/__manifest__.py
  cetmix_tower_server_queue/models/__init__.py
  cetmix_tower_server_queue/models/cx_tower_command_log.py
  cetmix_tower_server_queue/models/cx_tower_server.py
  cetmix_tower_server_queue/readme/newsfragments/.gitkeep
  cetmix_tower_server_queue/readme/newsfragments/4550.feature
  cetmix_tower_server_queue/tests/__init__.py
  cetmix_tower_server_queue/tests/test_command.py
  cetmix_tower_server_queue/views/cx_tower_command_log_view.xml
Labels: needs review, bot is merging ⏳, approved

#256 [16.0][MIG] cetmix_tower_server_queue
  cetmix_tower_server_queue/README.rst
  cetmix_tower_server_queue/__init__.py
  cetmix_tower_server_queue/__manifest__.py
  cetmix_tower_server_queue/i18n/cetmix_tower_server_queue.pot
  cetmix_tower_server_queue/i18n/it.po
  cetmix_tower_server_queue/models/__init__.py
  cetmix_tower_server_queue/models/cx_tower_command_log.py
  cetmix_tower_server_queue/models/cx_tower_server.py
  cetmix_tower_server_queue/pyproject.toml
  cetmix_tower_server_queue/readme/CONFIGURE.md
  cetmix_tower_server_queue/readme/DESCRIPTION.md
  cetmix_tower_server_queue/readme/HISTORY.md
  cetmix_tower_server_queue/readme/USAGE.md
  cetmix_tower_server_queue/readme/newsfragments/.gitkeep
  cetmix_tower_server_queue/static/description/icon.png
  cetmix_tower_server_queue/static/description/index.html
  cetmix_tower_server_queue/tests/__init__.py
  cetmix_tower_server_queue/tests/test_command.py
  cetmix_tower_server_queue/views/cx_tower_command_log_view.xml
Labels: needs review, bot is merging ⏳, approved

#258 [14.0][IMP] cetmix_tower_yaml: Add fields
  cetmix_tower/readme/newsfragments/4602.feature
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/models/cx_tower_shortcut.py
  cetmix_tower_yaml/models/cx_tower_variable_option.py
  cetmix_tower_yaml/readme/newsfragments/.gitkeep
  cetmix_tower_yaml/readme/newsfragments/4602.feature
  cetmix_tower_yaml/views/cx_tower_key_view.xml
Labels: needs review, bot is merging ⏳, approved

#259 [14.0][FIX] cetmix_tower_server: Key security
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4597.bugfix
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/newsfragments/4597.bugfix
  cetmix_tower_server/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#260 [16.0][IMP] cetmix_tower_yaml
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4602.feature
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/models/cx_tower_shortcut.py
  cetmix_tower_yaml/models/cx_tower_variable_option.py
  cetmix_tower_yaml/readme/newsfragments/4602.feature
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/views/cx_tower_key_view.xml
Labels: needs review, bot is merging ⏳, approved

#261 [16.0][FIX] cetmix_tower_server Secret values and view
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4601.bugfix
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/readme/newsfragments/4601.bugfix
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#262 [14.0][FIX] cetmix_tower_server
  README.md
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4547.feature
  cetmix_tower/readme/newsfragments/4612.bugfix
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/tools.py
  cetmix_tower_server/readme/DESCRIPTION.md
  cetmix_tower_server/readme/newsfragments/4547.feature
  cetmix_tower_server/readme/newsfragments/4612.bugfix
  cetmix_tower_server/security/cx_tower_variable_option_security.xml
  cetmix_tower_server/security/cx_tower_variable_security.xml
  cetmix_tower_server/security/cx_tower_variable_value_security.xml
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/__init__.py
  cetmix_tower_server/tests/test_cetmix_tower.py
  cetmix_tower_server/tests/test_tools.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
Labels: needs review, bot is merging ⏳, approved

#263 [16.0][IMP] cetmix_tower_server
  README.md
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4524.feature
  cetmix_tower/readme/newsfragments/4547.feature
  cetmix_tower/readme/newsfragments/4612.bugfix
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/tools.py
  cetmix_tower_server/readme/DESCRIPTION.md
  cetmix_tower_server/readme/newsfragments/4524.feature
  cetmix_tower_server/readme/newsfragments/4547.feature
  cetmix_tower_server/readme/newsfragments/4612.bugfix
  cetmix_tower_server/security/cx_tower_variable_option_security.xml
  cetmix_tower_server/security/cx_tower_variable_security.xml
  cetmix_tower_server/security/cx_tower_variable_value_security.xml
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/__init__.py
  cetmix_tower_server/tests/test_cetmix_tower.py
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/tests/test_tools.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#264 [14.0][FIX] cetmix_tower_server
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4574.bugfix
  cetmix_tower/readme/newsfragments/4574.feature
  cetmix_tower/readme/newsfragments/4617.bugfix
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/cx_tower_template_mixin.py
  cetmix_tower_server/readme/newsfragments/4574.bugfix
  cetmix_tower_server/readme/newsfragments/4574.feature
  cetmix_tower_server/readme/newsfragments/4617.bugfix
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/views/res_config_settings.xml
Labels: needs review, bot is merging ⏳, approved

#265 [16.0][FIX] cetmix_tower_server
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4574.bugfix
  cetmix_tower/readme/newsfragments/4574.feature
  cetmix_tower/readme/newsfragments/4617.bugfix
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/cx_tower_template_mixin.py
  cetmix_tower_server/readme/newsfragments/4574.bugfix
  cetmix_tower_server/readme/newsfragments/4574.feature
  cetmix_tower_server/readme/newsfragments/4617.bugfix
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/views/res_config_settings.xml
Labels: needs review, bot is merging ⏳, approved

#266 [14.0][IMP] cetmix_tower_server: get_host_key_value
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4264.feature
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/newsfragments/4264.feature
  cetmix_tower_server/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#269 [17.0][MIG] cetmix_tower_queue
  cetmix_tower_server_queue/README.rst
  cetmix_tower_server_queue/__init__.py
  cetmix_tower_server_queue/__manifest__.py
  cetmix_tower_server_queue/i18n/cetmix_tower_server_queue.pot
  cetmix_tower_server_queue/i18n/it.po
  cetmix_tower_server_queue/models/__init__.py
  cetmix_tower_server_queue/models/cx_tower_command_log.py
  cetmix_tower_server_queue/models/cx_tower_server.py
  cetmix_tower_server_queue/pyproject.toml
  cetmix_tower_server_queue/readme/CONFIGURE.md
  cetmix_tower_server_queue/readme/DESCRIPTION.md
  cetmix_tower_server_queue/readme/HISTORY.md
  cetmix_tower_server_queue/readme/USAGE.md
  cetmix_tower_server_queue/readme/newsfragments/.gitkeep
  cetmix_tower_server_queue/static/description/icon.png
  cetmix_tower_server_queue/static/description/index.html
  cetmix_tower_server_queue/tests/__init__.py
  cetmix_tower_server_queue/tests/test_command.py
  cetmix_tower_server_queue/views/cx_tower_command_log_view.xml
Labels: needs review, bot is merging ⏳, approved

#270 [17.0][MIG] cetmix_tower_server_notify_backend
  cetmix_tower_server_notify_backend/README.rst
  cetmix_tower_server_notify_backend/__init__.py
  cetmix_tower_server_notify_backend/__manifest__.py
  cetmix_tower_server_notify_backend/i18n/cetmix_tower_server_notify_backend.pot
  cetmix_tower_server_notify_backend/i18n/it.po
  cetmix_tower_server_notify_backend/models/__init__.py
  cetmix_tower_server_notify_backend/models/cx_tower_command_log.py
  cetmix_tower_server_notify_backend/models/cx_tower_plan_log.py
  cetmix_tower_server_notify_backend/pyproject.toml
  cetmix_tower_server_notify_backend/readme/CONFIGURE.md
  cetmix_tower_server_notify_backend/readme/DESCRIPTION.md
  cetmix_tower_server_notify_backend/readme/HISTORY.md
  cetmix_tower_server_notify_backend/readme/USAGE.md
  cetmix_tower_server_notify_backend/readme/newsfragments/.gitkeep
  cetmix_tower_server_notify_backend/static/description/icon.png
  cetmix_tower_server_notify_backend/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#274 [17.0][FIX] cetmix_tower_server: Fix kanban action
  cetmix_tower_server/views/cx_tower_server_view.xml
Labels: needs review, bot is merging ⏳, approved

#267 [14.0][FIX] cetmix_tower_server-hide_applicability_selector
  cetmix_tower_server/README.rst
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#277 [14.0][IMP] cetmix_tower_yaml: Rearrange groups
  cetmix_tower_yaml/security/cetmix_tower_yaml_groups.xml
Labels: needs review, bot is merging ⏳, approved

#276 [14.0][IMP] cetmix_tower-add_search_and_access_level_and_default_ssh
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#278 [16.0][IMP] cetmix_tower_server/yaml UI/UX updates
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4574.bugfix
  cetmix_tower/readme/newsfragments/4574.feature
  cetmix_tower/readme/newsfragments/4617.bugfix
  cetmix_tower/readme/newsfragments/4642.feature
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/data/ir_actions_server.xml
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/models/__init__.py
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/models/res_partner.py
  cetmix_tower_server/readme/newsfragments/4574.bugfix
  cetmix_tower_server/readme/newsfragments/4574.feature
  cetmix_tower_server/readme/newsfragments/4617.bugfix
  cetmix_tower_server/readme/newsfragments/4642.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/__init__.py
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/tests/test_partner_server_btn.py
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_key_view.xml
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/views/menuitems.xml
  cetmix_tower_server/views/res_partner_view.xml
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/readme/newsfragments/4642.feature
  cetmix_tower_yaml/security/cetmix_tower_yaml_groups.xml
  cetmix_tower_yaml/static/description/index.html
Labels: needs review, bot is merging ⏳, approved
