Repository cetmix/cetmix-tower, pull requests merged in 2025-03, with the labels that each got.

#211 [14.0][FIX] cetmix_tower_server: File access rules
  cetmix_tower_server/security/cx_tower_file_security.xml
Labels: needs review, bot is merging ⏳, approved

#209 [14.0][IMP] cetmix_tower_server: New system variables and YAML import updates
  cetmix_tower_server/models/cx_tower_variable_mixin.py
  cetmix_tower_yaml/models/cx_tower_command.py
  cetmix_tower_yaml/models/cx_tower_file_template.py
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_file_template.py
  cetmix_tower_yaml/tests/test_yaml_import_wizard.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.xml
Labels: needs review, bot is merging ⏳, approved

#206 [IMP] cetmix_tower_server: Refactor SSH handling
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/migrations/14.0.0.4.15/post-migration.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/ssh/__init__.py
  cetmix_tower_server/ssh/ssh.py
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/common.py
  cetmix_tower_server/tests/test_key.py
  cetmix_tower_server/tests/test_server_log.py
  cetmix_tower_server/tests/test_server_template.py
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#215 Translations update from Hosted Weblate
  cetmix_tower_git/i18n/hr.po
  cetmix_tower_server/i18n/hr.po
  cetmix_tower_yaml/i18n/hr.po
Labels: bot is merging ⏳

#228 [14.0][IMP] cetmix_tower_server: Variable form buttons
  cetmix_tower_server/models/cx_tower_template_mixin.py
  cetmix_tower_server/models/cx_tower_variable.py
  cetmix_tower_server/views/cx_tower_variable_view.xml
Labels: needs review, bot is merging ⏳, approved

#227 [14.0][IMP] cetmix_tower_server: New server wizard
  cetmix_tower_server/tests/test_server_template.py
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard.py
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#226 [IMP] cetmix_tower_key: SSH Server Auth Policy
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/CONFIGURE.md
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/ssh/ssh.py
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/wizards/__init__.py
  cetmix_tower_server/wizards/cx_tower_server_host_key_wizard.py
  cetmix_tower_server/wizards/cx_tower_server_host_key_wizard_view.xml
  cetmix_tower_server_notify_backend/README.rst
  cetmix_tower_server_notify_backend/readme/DESCRIPTION.md
  cetmix_tower_server_notify_backend/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#224 [14.0][IMP] cetmix_tower_server: use checkbox for sudo mode
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_execute_wizard_view.xml
Labels: bot is merging ⏳, approved, ready to merge

#225 [14.0][IMP][BREAKING] cx_tower_server: Refactor secrets
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/migrations/14.0.0.4.17/post-migration.py
  cetmix_tower_server/models/__init__.py
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/security/cx_tower_key_security.xml
  cetmix_tower_server/security/cx_tower_key_value_security.xml
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/common.py
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/tests/test_key.py
  cetmix_tower_server/tests/test_server.py
  cetmix_tower_server/views/cx_tower_key_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#230 [14.0][FIX][IMP] cetmix_tower_server: Fix migration issues, host key in templates, UX improvements
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/migrations/14.0.0.4.18/post-migration.py
  cetmix_tower_server/migrations/14.0.0.4.18/pre-migration.py
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/cx_tower_server_template_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard.py
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#232 [IMP] cetmix_tower_server: Post migration
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/migrations/14.0.0.4.19/post-migration.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/static/description/index.html
Labels: needs review, bot is merging ⏳

#229 [14.0][IMP] cetmix_tower_yaml: multi record support
  cetmix_tower_yaml/models/cx_tower_variable_value.py
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_file_template.py
  cetmix_tower_yaml/tests/test_plan.py
  cetmix_tower_yaml/tests/test_tower_yaml_mixin.py
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/tests/test_yaml_import_wizard.py
  cetmix_tower_yaml/views/cx_tower_command_view.xml
  cetmix_tower_yaml/views/cx_tower_file_template_view.xml
  cetmix_tower_yaml/views/cx_tower_plan_view.xml
  cetmix_tower_yaml/views/cx_tower_server_template_view.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz_upload.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#234 [14.0][IMP] cetmix_tower_server: variable value modifier
  cetmix_tower_server/models/cx_tower_variable.py
  cetmix_tower_server/models/cx_tower_variable_mixin.py
  cetmix_tower_server/models/cx_tower_variable_value.py
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/views/cx_tower_variable_view.xml
Labels: needs review, bot is merging ⏳, approved

#236 [14.0][FIX] cetmix_tower_server: Variable modifier
  cetmix_tower_server/models/cx_tower_variable_mixin.py
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/views/cx_tower_variable_view.xml
Labels: needs review, bot is merging ⏳, approved
