Repository cetmix/cetmix-tower, pull requests merged in 2025-08, with the labels that each got.

#368 [16.0][FIX] cetmix_tower_server: fix file template creation
  cetmix_tower_server/models/cx_tower_file_template.py
Labels: needs review, bot is merging ⏳, approved

#367 [17.0][IMP] cetmix_tower_server Options in file commands
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_file_template.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/readme/newsfragments/4740.feature
  cetmix_tower_server/tests/common.py
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/tests/test_file.py
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_scheduled_task_view.xml
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard_view.xml
  cetmix_tower_server_queue/views/cx_tower_file_view.xml
  cetmix_tower_yaml/models/cx_tower_command.py
  cetmix_tower_yaml/readme/newsfragments/4740.feature
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
Labels: needs review, bot is merging ⏳, approved

#370 [17.0][MIG] cetmix_tower_aws: Migration to 17.0
  cetmix_tower_aws/README.rst
  cetmix_tower_aws/__init__.py
  cetmix_tower_aws/__manifest__.py
  cetmix_tower_aws/demo/demo_data.xml
  cetmix_tower_aws/i18n/cetmix_tower_aws.pot
  cetmix_tower_aws/i18n/it.po
  cetmix_tower_aws/models/__init__.py
  cetmix_tower_aws/models/cx_tower_command.py
  cetmix_tower_aws/pyproject.toml
  cetmix_tower_aws/readme/CONFIGURE.md
  cetmix_tower_aws/readme/CONTEXT.md
  cetmix_tower_aws/readme/DESCRIPTION.md
  cetmix_tower_aws/readme/HISTORY.md
  cetmix_tower_aws/readme/USAGE.md
  cetmix_tower_aws/readme/newsfragments/.gitkeep
  cetmix_tower_aws/static/description/banner.png
  cetmix_tower_aws/static/description/icon.png
  cetmix_tower_aws/static/description/index.html
  cetmix_tower_aws/tests/__init__.py
  cetmix_tower_aws/tests/test_boto3_integration.py
  requirements.txt
Labels: needs review, bot is merging ⏳

#371 [17.0][FIX] cetmix_tower_server Python imports
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/readme/newsfragments/4891.bugfix
  requirements.txt
Labels: needs review, bot is merging ⏳, approved

#372 [16.0][FIX] cetmix_tower_server Python imports
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/readme/newsfragments/4891.bugfix
  requirements.txt
Labels: needs review, bot is merging ⏳, approved

#364 [14.0][MIG] cetmix_tower: back port updates from 16.0
  cetmix_tower_git/readme/newsfragments/4849.feature
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_yaml/models/cx_tower_server.py
  cetmix_tower_yaml/tests/__init__.py
  cetmix_tower_yaml/tests/test_server_yaml.py
Labels: needs review, bot is merging ⏳

#378 [17.0][FIX] cetmix_tower_yaml File upload
  cetmix_tower_yaml/readme/newsfragments/4899.bugfix
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz_upload.py
Labels: needs review, bot is merging ⏳, approved

#374 [16.0][FIX] cetmix_tower_server: important updates
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/models/cx_tower_server_log.py
  cetmix_tower_server/models/res_partner.py
  cetmix_tower_server/readme/newsfragments/4866.feature
  cetmix_tower_server/security/cx_tower_server_wizard_access_rules.xml
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/tests/test_command_log.py
  cetmix_tower_server/tests/test_plan_log.py
  cetmix_tower_server/tests/test_server_log.py
  cetmix_tower_server/views/res_partner_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#380 [17.0][IMP] Update website url in all modules
  cetmix_tower/README.rst
  cetmix_tower/__manifest__.py
  cetmix_tower/readme/HISTORY.md
  cetmix_tower/readme/newsfragments/.gitkeep
  cetmix_tower_aws/__manifest__.py
  cetmix_tower_git/__manifest__.py
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server_notify_backend/__manifest__.py
  cetmix_tower_server_queue/__manifest__.py
  cetmix_tower_yaml/__manifest__.py
Labels: needs review, bot is merging ⏳

#381 [17.0][MIG] cetmix_tower_server: forward port updates
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/models/cx_tower_server_log.py
  cetmix_tower_server/models/res_partner.py
  cetmix_tower_server/readme/newsfragments/4866.feature
  cetmix_tower_server/security/cx_tower_server_wizard_access_rules.xml
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/tests/test_command_log.py
  cetmix_tower_server/tests/test_plan_log.py
  cetmix_tower_server/tests/test_server_log.py
  cetmix_tower_server/views/res_partner_view.xml
Labels: needs review, bot is merging ⏳, approved

#356 [16.0][IMP] cetmix_tower: Search servers by git remote
  cetmix_tower_git/models/__init__.py
  cetmix_tower_git/models/cetmix_tower.py
  cetmix_tower_git/models/cx_tower_server.py
  cetmix_tower_git/readme/newsfragments/4838.feature
  cetmix_tower_git/tests/__init__.py
  cetmix_tower_git/tests/test_cetmix_tower.py
  cetmix_tower_git/tests/test_tower_git_ref.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#387 [16.0][i18n] italian update
  cetmix_tower_aws/i18n/it.po
  cetmix_tower_git/i18n/it.po
  cetmix_tower_ovh/i18n/it.po
  cetmix_tower_server/i18n/it.po
  cetmix_tower_server_queue/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: merged 🎉

#376 [16.0][FIX] cetmix_tower_yaml: important updates
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/migrations/16.0.1.4.1/post-migration.py
  cetmix_tower_yaml/models/cx_tower_yaml_manifest_template.py
  cetmix_tower_yaml/readme/newsfragments/4896.bugfix
  cetmix_tower_yaml/security/cx_tower_yaml_wizard_access_rules.xml
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/views/cx_tower_yaml_manifest_template_views.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.xml
Labels: needs review, bot is merging ⏳, approved

#391 [17.0][MIG] cetmix_tower_yaml: cetmix_tower_server: forward port from 16.0
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/migrations/17.0.1.4.1/post-migration.py
  cetmix_tower_yaml/models/cx_tower_yaml_manifest_template.py
  cetmix_tower_yaml/readme/newsfragments/4896.bugfix
  cetmix_tower_yaml/security/cx_tower_yaml_wizard_access_rules.xml
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/views/cx_tower_yaml_manifest_template_views.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.xml
Labels: needs review, bot is merging ⏳, approved
