Repository cetmix/cetmix-tower, pull requests merged in 2025-06, with the labels that each got.

#305 [16.0] update i18n italy
  cetmix_tower_aws/i18n/it.po
  cetmix_tower_git/i18n/it.po
  cetmix_tower_server/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: bot is merging ⏳

#304 [14.0] update i18n italy
  cetmix_tower_aws/i18n/it.po
  cetmix_tower_ovh/i18n/it.po
  cetmix_tower_server/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: bot is merging ⏳

#272 [14.0][IMP] cetmix_tower_server_queue-async_file_operations
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/3720.feature
  cetmix_tower_server/models/constants.py
  cetmix_tower_server/models/cx_tower_file.py
  cetmix_tower_server/tests/common.py
  cetmix_tower_server_queue/README.rst
  cetmix_tower_server_queue/__manifest__.py
  cetmix_tower_server_queue/models/__init__.py
  cetmix_tower_server_queue/models/cx_tower_file.py
  cetmix_tower_server_queue/readme/newsfragments/3720.feature
  cetmix_tower_server_queue/static/description/index.html
  cetmix_tower_server_queue/tests/__init__.py
  cetmix_tower_server_queue/tests/test_file.py
  cetmix_tower_server_queue/views/cx_tower_file_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#311 [IMP] cetmix_tower_server_queue: copy job error to command log
  cetmix_tower_server_queue/models/queue_job.py
Labels: needs review, bot is merging ⏳, approved

#316 [17.0][i18n] italian translation
  cetmix_tower_git/i18n/it.po
  cetmix_tower_server/i18n/it.po
  cetmix_tower_server_queue/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: bot is merging ⏳

#318 [16.0][IMP] cetmix_tower_server-improve_UX_of_command_form
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/readme/newsfragments/4753.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/cx_tower_command_view.xml
Labels: needs review, bot is merging ⏳, approved

#312 [16.0][IMP] cetmix_tower_yaml: Performance export
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/readme/newsfragments/4728.feature
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/tests/test_yaml_import_wizard.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#319 [16.0][IMP] cetmix_tower_server-enforce_required_variables
  cetmix_tower_server/README.rst
  cetmix_tower_server/readme/newsfragments/4779.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/views/cx_tower_variable_value_view.xml
  cetmix_tower_server/views/cx_tower_variable_view.xml
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge

#323 [14.0][IMP] cetmix_tower_yaml: Backport updates from 16.0
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/models/cx_tower_file.py
  cetmix_tower_yaml/models/cx_tower_server_log.py
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/readme/newsfragments/4728.feature
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/__init__.py
  cetmix_tower_yaml/tests/test_server_log.py
  cetmix_tower_yaml/tests/test_tower_yaml_mixin.py
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/tests/test_yaml_import_wizard.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.py
Labels: needs review, bot is merging ⏳, approved

#321 [16.0][FIX] cetmix_tower_server-variable_reference_change
  cetmix_tower_server/models/cx_tower_variable.py
  cetmix_tower_server/tests/test_variable.py
Labels: needs review, bot is merging ⏳, approved
