Repository cetmix/cetmix-tower, pull requests merged in 2025-05, with the labels that each got.

#282 [16.0] i18n italy update
  cetmix_tower_git/i18n/it.po
  cetmix_tower_server/i18n/it.po
  cetmix_tower_server_notify_backend/i18n/it.po
  cetmix_tower_server_queue/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: bot is merging ⏳

#283 [14.0] i18n italy update
  cetmix_tower_git/i18n/it.po
  cetmix_tower_server/i18n/it.po
  cetmix_tower_server_queue/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: bot is merging ⏳

#281 [14.0][FIX] updates based on the migration backlog
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4611.bugfix
  cetmix_tower_git/models/cx_tower_git_project.py
  cetmix_tower_git/readme/newsfragments/.gitkeep
  cetmix_tower_git/readme/newsfragments/4611.bugfix
  cetmix_tower_git/tests/test_source.py
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/models/cx_tower_reference_mixin.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/readme/newsfragments/4611.bugfix
  cetmix_tower_server/views/cx_tower_key_view.xml
  cetmix_tower_server/views/cx_tower_server_template_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
  cetmix_tower_server_queue/README.rst
  cetmix_tower_server_queue/models/cx_tower_command_log.py
  cetmix_tower_server_queue/readme/newsfragments/4611.bugfix
  cetmix_tower_server_queue/static/description/index.html
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/readme/newsfragments/4611.bugfix
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/test_tower_yaml_mixin.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz_upload.py
Labels: needs review, bot is merging ⏳, approved

#280 [17.0][IMP] cetmix_tower_server/yaml UI/UX improvements
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4647.feature
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/data/ir_actions_server.xml
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/models/__init__.py
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/models/res_partner.py
  cetmix_tower_server/readme/newsfragments/4647.feature
  cetmix_tower_server/tests/__init__.py
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/tests/test_partner_server_btn.py
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_key_view.xml
  cetmix_tower_server/views/cx_tower_plan_view.xml
  cetmix_tower_server/views/cx_tower_server_template_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/views/menuitems.xml
  cetmix_tower_server/views/res_partner_view.xml
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/readme/newsfragments/4647.feature
  cetmix_tower_yaml/security/cetmix_tower_yaml_groups.xml
  cetmix_tower_yaml/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#275 [ADD] cetmix_tower_aws: add module
  cetmix_tower_aws/README.rst
  cetmix_tower_aws/__init__.py
  cetmix_tower_aws/__manifest__.py
  cetmix_tower_aws/models/__init__.py
  cetmix_tower_aws/models/constants.py
  cetmix_tower_aws/models/cx_tower_command.py
  cetmix_tower_aws/readme/CONFIGURE.md
  cetmix_tower_aws/readme/CONTEXT.md
  cetmix_tower_aws/readme/DESCRIPTION.md
  cetmix_tower_aws/readme/USAGE.md
  cetmix_tower_aws/static/description/icon.png
  cetmix_tower_aws/tests/__init__.py
  cetmix_tower_aws/tests/test_boto3_integration.py
  requirements.txt
  setup/cetmix_tower_aws/odoo/addons/cetmix_tower_aws
  setup/cetmix_tower_aws/setup.py
Labels: needs review, bot is merging ⏳, approved, ready to merge

#287 [FIX] cetmix_tower_aws: fix enumerated list error
  cetmix_tower_aws/README.rst
  cetmix_tower_aws/readme/CONFIGURE.md
  cetmix_tower_aws/readme/USAGE.md
  cetmix_tower_aws/static/description/index.html
Labels: needs review, bot is merging ⏳

#285 [16.0][IMP] forward port updates
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4663.bugfix
  cetmix_tower_git/README.rst
  cetmix_tower_git/models/cx_tower_git_project.py
  cetmix_tower_git/readme/newsfragments/4663.bugfix
  cetmix_tower_git/static/description/index.html
  cetmix_tower_git/tests/test_source.py
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_reference_mixin.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_server_log.py
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/readme/newsfragments/4663.bugfix
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/views/cx_tower_server_template_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard_view.xml
  cetmix_tower_server/wizards/cx_tower_server_template_create_wizard_view.xml
  cetmix_tower_server_queue/README.rst
  cetmix_tower_server_queue/models/cx_tower_command_log.py
  cetmix_tower_server_queue/readme/newsfragments/4611.bugfix
  cetmix_tower_server_queue/static/description/index.html
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/readme/newsfragments/4663.bugfix
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/test_tower_yaml_mixin.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz_upload.py
Labels: needs review, bot is merging ⏳, approved

#279 [14.0][IMP] cetmix_tower_server-add_no_split_for_sudo
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4641.feature
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/newsfragments/4641.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_yaml/models/cx_tower_command.py
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
Labels: needs review, bot is merging ⏳, approved

#288 [14.0][FIX] cetmix_tower_server Command Run Wizard
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4678.feature
  cetmix_tower/readme/newsfragments/4679.bugfix
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/newsfragments/4678.feature
  cetmix_tower_server/readme/newsfragments/4679.bugfix
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server_queue/README.rst
  cetmix_tower_server_queue/models/cx_tower_server.py
  cetmix_tower_server_queue/readme/newsfragments/4678.feature
  cetmix_tower_server_queue/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#291 [16.0][REF] cetmix_tower_server Key value storage
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4686.feature
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/readme/newsfragments/4686.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_key.py
Labels: needs review, merged 🎉, approved

#289 [IMP] cetmix_tower_aws: banner and description add
  cetmix_tower_aws/README.rst
  cetmix_tower_aws/__manifest__.py
  cetmix_tower_aws/models/constants.py
  cetmix_tower_aws/models/cx_tower_command.py
  cetmix_tower_aws/readme/CONFIGURE.md
  cetmix_tower_aws/readme/USAGE.md
  cetmix_tower_aws/static/description/banner.png
  cetmix_tower_aws/static/description/index.html
  cetmix_tower_aws/tests/test_boto3_integration.py
Labels: needs review, bot is merging ⏳, approved

#293 [17.0][IMP] cetmix_tower_server/yaml/git/queue Forward port updates
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4641.feature
  cetmix_tower/readme/newsfragments/4670.feature
  cetmix_tower/readme/newsfragments/4678.feature
  cetmix_tower/readme/newsfragments/4679.bugfix
  cetmix_tower/readme/newsfragments/4686.feature
  cetmix_tower_git/README.rst
  cetmix_tower_git/models/cx_tower_git_project_rel.py
  cetmix_tower_git/models/cx_tower_server.py
  cetmix_tower_git/readme/newsfragments/4670.feature
  cetmix_tower_git/static/description/index.html
  cetmix_tower_server/README.rst
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/migrations/16.0.1.0.6/post-migration.py
  cetmix_tower_server/migrations/17.0.1.0.2/post-migration.py
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_file.py
  cetmix_tower_server/models/cx_tower_key.py
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_server_log.py
  cetmix_tower_server/readme/newsfragments/4641.feature
  cetmix_tower_server/readme/newsfragments/4670.feature
  cetmix_tower_server/readme/newsfragments/4678.feature
  cetmix_tower_server/readme/newsfragments/4679.bugfix
  cetmix_tower_server/readme/newsfragments/4686.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command.py
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/tests/test_file.py
  cetmix_tower_server/tests/test_key.py
  cetmix_tower_server/views/cx_tower_command_view.xml
  cetmix_tower_server/views/cx_tower_file_view.xml
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard_view.xml
  cetmix_tower_server_queue/README.rst
  cetmix_tower_server_queue/models/cx_tower_server.py
  cetmix_tower_server_queue/readme/newsfragments/4678.feature
  cetmix_tower_server_queue/static/description/index.html
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/models/__init__.py
  cetmix_tower_yaml/models/cx_tower_command.py
  cetmix_tower_yaml/models/cx_tower_file.py
  cetmix_tower_yaml/models/cx_tower_server.py
  cetmix_tower_yaml/models/cx_tower_yaml_mixin.py
  cetmix_tower_yaml/readme/newsfragments/4670.feature
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/test_command.py
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/tests/test_yaml_import_wizard.py
  cetmix_tower_yaml/views/cx_tower_server_view.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.py
Labels: needs review, bot is merging ⏳, approved

#294 [14.0][IMP] cetmix_tower_server/yaml Secret Key Values
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4696.feature
  cetmix_tower/readme/newsfragments/4699.feature
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/newsfragments/4696.feature
  cetmix_tower_server/readme/newsfragments/4699.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/test_command_wizard.py
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard_view.xml
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/models/__init__.py
  cetmix_tower_yaml/models/cx_tower_key_value.py
  cetmix_tower_yaml/readme/newsfragments/4696.feature
  cetmix_tower_yaml/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#296 [16.0][IMP] cetmix_tower_server/yaml Forward port updates
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4696.feature
  cetmix_tower/readme/newsfragments/4699.feature
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_key_value.py
  cetmix_tower_server/readme/newsfragments/4696.feature
  cetmix_tower_server/readme/newsfragments/4699.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/models/__init__.py
  cetmix_tower_yaml/models/cx_tower_key_value.py
  cetmix_tower_yaml/readme/newsfragments/4696.feature
  cetmix_tower_yaml/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#292 [16.0][MIG] cetmix_tower_aws: Migration to 16.0
  cetmix_tower_aws/README.rst
  cetmix_tower_aws/__init__.py
  cetmix_tower_aws/__manifest__.py
  cetmix_tower_aws/demo/demo_data.xml
  cetmix_tower_aws/i18n/cetmix_tower_aws.pot
  cetmix_tower_aws/models/__init__.py
  cetmix_tower_aws/models/constants.py
  cetmix_tower_aws/models/cx_tower_command.py
  cetmix_tower_aws/pyproject.toml
  cetmix_tower_aws/readme/CONFIGURE.md
  cetmix_tower_aws/readme/CONTEXT.md
  cetmix_tower_aws/readme/DESCRIPTION.md
  cetmix_tower_aws/readme/USAGE.md
  cetmix_tower_aws/static/description/banner.png
  cetmix_tower_aws/static/description/icon.png
  cetmix_tower_aws/static/description/index.html
  cetmix_tower_aws/tests/__init__.py
  cetmix_tower_aws/tests/test_boto3_integration.py
  requirements.txt
Labels: needs review, bot is merging ⏳, approved, ready to merge

#298 [16.0][FIX] cetmix_tower_server Set field values for file with no server
  cetmix_tower/README.rst
  cetmix_tower/readme/newsfragments/4715.bugfix
  cetmix_tower_git/README.rst
  cetmix_tower_git/models/cx_tower_file.py
  cetmix_tower_git/models/cx_tower_server.py
  cetmix_tower_git/readme/newsfragments/4715.bugfix
  cetmix_tower_git/static/description/index.html
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_file.py
  cetmix_tower_server/readme/newsfragments/4715.bugfix
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/cx_tower_file_view.xml
Labels: needs review, bot is merging ⏳, approved

#295 [16.0][IMP] cetmix_tower_server-command_log_view_update
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/readme/newsfragments/4697.feature
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/views/cx_tower_command_log_view.xml
  cetmix_tower_server/views/cx_tower_plan_log_view.xml
  cetmix_tower_server/views/cx_tower_plan_view.xml
Labels: needs review, bot is merging ⏳, approved

#297 [14.0][ADD] cetmix_tower_ovh: Cetmix Tower OVH integration
  cetmix_tower_ovh/README.rst
  cetmix_tower_ovh/__init__.py
  cetmix_tower_ovh/__manifest__.py
  cetmix_tower_ovh/demo/demo_data.xml
  cetmix_tower_ovh/models/__init__.py
  cetmix_tower_ovh/models/constants.py
  cetmix_tower_ovh/models/cx_tower_command.py
  cetmix_tower_ovh/readme/CONFIGURE.md
  cetmix_tower_ovh/readme/CONTEXT.md
  cetmix_tower_ovh/readme/DESCRIPTION.md
  cetmix_tower_ovh/readme/USAGE.md
  cetmix_tower_ovh/static/description/icon.png
  cetmix_tower_ovh/static/description/index.html
  cetmix_tower_ovh/tests/__init__.py
  cetmix_tower_ovh/tests/test_ovh_integration.py
  requirements.txt
  setup/cetmix_tower_ovh/odoo/addons/cetmix_tower_ovh
  setup/cetmix_tower_ovh/setup.py
Labels: bot is merging ⏳, approved, ready to merge
