Repository cetmix/cetmix-tower, pull requests merged in 2025-07, with the labels that each got.

#328 [17.0][IMP] cetmix_tower_server/yaml: Forward port updates from 16.0
  cetmix_tower_server/README.rst
  cetmix_tower_server/__manifest__.py
  cetmix_tower_server/data/ir_cron.xml
  cetmix_tower_server/demo/demo_data.xml
  cetmix_tower_server/models/__init__.py
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/models/cx_tower_plan_log.py
  cetmix_tower_server/models/cx_tower_scheduled_task.py
  cetmix_tower_server/models/cx_tower_scheduled_task_cv.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/models/cx_tower_server_template.py
  cetmix_tower_server/models/res_config_settings.py
  cetmix_tower_server/readme/newsfragments/4650.feature
  cetmix_tower_server/security/cx_tower_scheduled_task_cv_security.xml
  cetmix_tower_server/security/cx_tower_scheduled_task_security.xml
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/static/description/index.html
  cetmix_tower_server/tests/__init__.py
  cetmix_tower_server/tests/common.py
  cetmix_tower_server/tests/test_scheduled_task.py
  cetmix_tower_server/views/cx_tower_command_log_view.xml
  cetmix_tower_server/views/cx_tower_plan_log_view.xml
  cetmix_tower_server/views/cx_tower_scheduled_task_view.xml
  cetmix_tower_server/views/cx_tower_server_template_view.xml
  cetmix_tower_server/views/cx_tower_server_view.xml
  cetmix_tower_server/views/menuitems.xml
  cetmix_tower_server/views/res_config_settings.xml
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/models/__init__.py
  cetmix_tower_yaml/models/cx_tower_scheduled_task.py
  cetmix_tower_yaml/models/cx_tower_server.py
  cetmix_tower_yaml/models/cx_tower_server_template.py
  cetmix_tower_yaml/readme/newsfragments/4650.feature
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/views/cx_tower_scheduled_task_view.xml
Labels: needs review, bot is merging ⏳, approved

#326 [17.0][IMP] cetmix_tower_server: Forward port updates from 16.0
  cetmix_tower_server/README.rst
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/newsfragments/4747.bugfix
  cetmix_tower_server/static/description/index.html
Labels: needs review, bot is merging ⏳, approved

#329 [16.0][FIX] cetmix_tower-restore_flight_plan_order
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/readme/newsfragments/4816.bugfix
  cetmix_tower_server/views/cx_tower_command_log_view.xml
Labels: needs review, bot is merging ⏳

#332 [14.0] i18n update for Italian
  cetmix_tower_aws/i18n/it.po
  cetmix_tower_ovh/i18n/it.po
  cetmix_tower_server/i18n/it.po
  cetmix_tower_server_queue/i18n/it.po
Labels: bot is merging ⏳

#331 [16.0] i18n update for Italian
  cetmix_tower_server/i18n/it.po
  cetmix_tower_yaml/i18n/it.po
Labels: bot is merging ⏳

#333 [16.0][FIX] cetmix_tower_yaml-bypass_SSH_check
  cetmix_tower_yaml/README.rst
  cetmix_tower_yaml/readme/newsfragments/4812.bugfix
  cetmix_tower_yaml/static/description/index.html
  cetmix_tower_yaml/tests/test_yaml_import_wizard.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.py
Labels: needs review, bot is merging ⏳, approved

#335 [FIX] cetmix_tower_yaml: Missing import model name
  cetmix_tower_yaml/readme/newsfragments/4820.bugfix
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
Labels: needs review, bot is merging ⏳, approved

#348 [17.0][MIG] cetmix_tower_yaml: forward port updates from 16.0
  cetmix_tower_yaml/__manifest__.py
  cetmix_tower_yaml/models/__init__.py
  cetmix_tower_yaml/models/cx_tower_yaml_manifest_author.py
  cetmix_tower_yaml/models/cx_tower_yaml_manifest_template.py
  cetmix_tower_yaml/security/ir.model.access.csv
  cetmix_tower_yaml/tests/test_yaml_export_wizard.py
  cetmix_tower_yaml/views/cx_tower_yaml_manifest_author_views.xml
  cetmix_tower_yaml/views/cx_tower_yaml_manifest_template_views.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_export_wiz.xml
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.py
  cetmix_tower_yaml/wizards/cx_tower_yaml_import_wiz.xml
Labels: needs review, bot is merging ⏳, approved

#355 [17.0][MIG] cetmix_tower_server: Forward port updates from 16.0
  cetmix_tower_server/models/__init__.py
  cetmix_tower_server/models/cetmix_tower.py
  cetmix_tower_server/models/constants.py
  cetmix_tower_server/models/cx_tower_command.py
  cetmix_tower_server/models/cx_tower_command_log.py
  cetmix_tower_server/models/cx_tower_custom_variable_value_mixin.py
  cetmix_tower_server/models/cx_tower_plan.py
  cetmix_tower_server/models/cx_tower_plan_log.py
  cetmix_tower_server/models/cx_tower_scheduled_task_cv.py
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/security/ir.model.access.csv
  cetmix_tower_server/tests/test_plan.py
  cetmix_tower_server/wizards/cx_tower_command_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard.py
  cetmix_tower_server/wizards/cx_tower_plan_run_wizard_view.xml
Labels: needs review, bot is merging ⏳, approved

#357 [16.0][IMP]cetmix_tower_server: ace_tower add select secrets
  cetmix_tower_server/readme/newsfragments/4853.feature.md
  cetmix_tower_server/static/src/components/ace_variables/ace_variables.esm.js
  cetmix_tower_server/static/src/components/ace_variables/ace_variables.xml
  cetmix_tower_server/static/src/components/ace_variables/autocomplete_popup.esm.js
  cetmix_tower_server/static/src/components/ace_variables/autocomplete_popup.xml
Labels: bot is merging ⏳, approved

#353 [14.0][FIX] cetmix_tower_server: Python command
  cetmix_tower_server/models/cx_tower_command.py
Labels: needs review, bot is merging ⏳

#361 [16.0][IMP] cetmix_tower_server References in files
  cetmix_tower_server/models/cx_tower_file.py
  cetmix_tower_server/readme/newsfragments/4870.feature
  cetmix_tower_server/views/cx_tower_file_template_view.xml
  cetmix_tower_server/views/cx_tower_file_view.xml
Labels: needs review, bot is merging ⏳, approved

#315 [14.0][IMP] cetmix_tower_git-link/copy git project on file command
  cetmix_tower_git/__manifest__.py
  cetmix_tower_git/models/__init__.py
  cetmix_tower_git/models/cx_tower_plan_line.py
  cetmix_tower_git/models/cx_tower_server.py
  cetmix_tower_git/readme/newsfragments/4759.feature
  cetmix_tower_git/tests/__init__.py
  cetmix_tower_git/tests/test_server.py
  cetmix_tower_git/views/cx_tower_plan_line_view.xml
  cetmix_tower_server/models/cx_tower_server.py
  cetmix_tower_server/readme/newsfragments/4759.feature
Labels: needs review, bot is merging ⏳

#354 [17.0][MIG] cetmix_tower_server_queue: forward port updates
  cetmix_tower_server/models/constants.py
  cetmix_tower_server/models/cx_tower_file.py
  cetmix_tower_server/tests/common.py
  cetmix_tower_server_queue/__manifest__.py
  cetmix_tower_server_queue/models/__init__.py
  cetmix_tower_server_queue/models/cx_tower_command_log.py
  cetmix_tower_server_queue/models/cx_tower_file.py
  cetmix_tower_server_queue/models/queue_job.py
  cetmix_tower_server_queue/readme/newsfragments/3720.feature
  cetmix_tower_server_queue/readme/newsfragments/4718.feature
  cetmix_tower_server_queue/tests/__init__.py
  cetmix_tower_server_queue/tests/test_command_log.py
  cetmix_tower_server_queue/tests/test_file.py
  cetmix_tower_server_queue/views/cx_tower_file_view.xml
Labels: needs review, bot is merging ⏳, approved, ready to merge
